-- require("user.setting.lualine.lag_lualine")
-- require("user.setting.lualine.evil_line")
-- require("user.setting.lualine.bubbles")
require("user.setting.lualine.loneExile_bl")
-- require("user.setting.lualine.ex")
